spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.109.197.221:3306/admin-template
    username: admin-template
    password: ynnh3KDW8FfkXARK
  data:
    redis:
      host: 47.109.197.221
      port: 6379
      password: 123456